// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Carrega as fontes do Google com variáveis CSS
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadados da aplicação
export const metadata: Metadata = {
  title: "Ficha de criação de personagem",
  description: "Generated by create next app",
};

// Exporte apenas o RootLayout como default export
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        // Utiliza as variáveis das fontes e aplica estilos básicos
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* Container principal com estilo para melhorar a UI */}
        <div className="min-h-screen bg-gray-900 text-gray-100">
          <header className="bg-gray-800 p-4">
            <h1 className="text-3xl font-bold text-center">Meu Projeto de Fichas de RPG</h1>
          </header>
          <main className="max-w-5xl mx-auto p-6">
            {children}
          </main>
          <footer className="bg-gray-800 p-4 text-center text-sm text-gray-400">
            © {new Date().getFullYear()} Meu Projeto de RPG
          </footer>
        </div>
      </body>
    </html>
  );
}
